apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: cluster.k8s-ruan-us-east-1.domain.io
  name: bastion-us-east-1
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  cloudLabels:
    project: ruan
    environment: k8s-ruan-us-east-1
  machineType: t2.micro
  # use spot instance
  maxPrice: "0.0116"
  maxSize: 1
  minSize: 1
  role: Bastion
  subnets:
  - utility-us-east-1a
  - utility-us-east-1b
  - utility-us-east-1c
  # CHANGEME
  additionalUserData:
  - name: somescript.sh
    type: text/x-shellscript
    content: |
      #!/bin/sh
      content here
