apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: cluster.k8s-ruan-us-east-1.domain.io
  name: master-us-east-1a
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  cloudLabels:
    project: ruan
    environment: k8s-ruan-us-east-1
  machineType: t2.medium
  # use spot instance
  maxPrice: "0.046"
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - private-us-east-1a
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: cluster.k8s-ruan-us-east-1.domain.io
  name: master-us-east-1b
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  cloudLabels:
    project: ruan
    environment: k8s-ruan-us-east-1
  machineType: t2.medium
  # use spot instance
  maxPrice: "0.046"
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - private-us-east-1b
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: cluster.k8s-ruan-us-east-1.domain.io
  name: master-us-east-1c
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  cloudLabels:
    project: ruan
    environment: k8s-ruan-us-east-1
  machineType: t2.medium
  # use spot instance
  maxPrice: "0.046"
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - private-us-east-1c
