language: go
go:
  - 1.10
  - master
install: true
matrix:
  allow_failures:
    - go: master
  fast_finish: true
script:
  - go test -v -race ./...                   # Run all the tests with the race detector enabled
  - go vet ./...                             # go vet is the official Go static analyzer
notifications:
  email: 
    recipients:
      - ruanarcega@gmail.com
    on_success: never
    on_failure: always